# Generated by Django 2.2.12 on 2020-06-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0005_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adicionais', models.TextField(max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_categoria', to='aplicativo.Categoria_produto', verbose_name='Categoria do produto')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='aplicativo.Loja', verbose_name='Loja')),
            ],
        ),
    ]
