# Generated by Django 2.2.12 on 2020-06-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='adicionais',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
